spring.application.name=userservice

## PostgreSQL
# spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/user_service
spring.datasource.username=root
spring.datasource.password=root

## JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

## Init DB
# spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:sql/initiate.sql,classpath:sql/sample_records.sql
# spring.sql.init.data-locations=classpath:sql/initiate.sql

## Logging level
# logging.level.org.springframework.web=DEBUG

## JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

